# Generated by Django 5.2.5 on 2025-11-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('coleccionista', 'Coleccionista'), ('visitante', 'Visitante')], default='visitante', max_length=20),
        ),
    ]
